### ISSUE TITLE
Demography plots misses child populations. 

### ISSUE THREAD

**Issue by ThomasGaub** [Open-Systems-Pharmacology/OSPSuite.ReportingEngine#318]
Demography plots misses child populations. 
for attached populations

[Test_NO10.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/files/5150938/Test_NO10.zip)

**Comment by pchelle** [comment]
The child populations do appear.
However, since the populations are small and span a lot of Age altogether, the default binning used for aggregation of the percentile does not work great and ends up providing 1 unique bin for each child population.
As a consequence, the ribbon is empty and you should receive warning messages from `ggplot2` such as: 
`geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?`

**Comment by pchelle** [comment]
It is possible to overwrite the default binning by playing with the "plotDemography" task settings.
We merged a pull request yesterday that includes a draft version of a vignette explaining how to play with such settings.
The vignette is called "plot-settings" and some feedback on how to improve it would be great. (if you can't get it with the latest version of the package, I can send it to you by email).

The current way of updating the binning of the age parameter for your workflow is to write:
`popModelWF$plotDemography$settings$xParametersBreaks[[StandardPath$Age]] <- seq(0,100,0.5)`
In this example, I binned providing a simple vector of edges, but if you provide one number, it will be the number of bins.
If you provide a more sophisticated vector the edges may render a nicer plot.

**Comment by ThomasGaub** [comment]
Thanks for the information will try this out. 
We should reconsider the bin algorithm for a futur version.

**Comment by ThomasGaub** [comment]
@pchelle 
Can you please provide some more information how to use the property.
Most imprtant how can I give Intervalls I know. 
Didn't manage to do this.

**Comment by pchelle** [comment]
__`xParametersBreaks`__ should be a named list.
The names of the list should be the demography parameter paths names, hence __`[[StandardPath$Age]]`__ which is equivalent to __`[["Organism|Age"]]`__.
If the list element is one number you will bin all your data into that number of bins
- For instance, `xParametersBreaks[[StandardPath$Age]] <- 5` splits the Age in 5 equal bins
If the list element is a vector number you will bin all your data into the bins delimited by the numbers 
- For instance, `xParametersBreaks[[StandardPath$Age]] <- c(0, 1, 2, 5, 10, 20, 50, 100)` splits the Age into the following bins:  [0, 1), [1, 2), [2, 5), [5, 10) ... [50, 100).
__Note__: if you have no data in a some the bins, these very data bins will just not be plotted

**Comment by ThomasGaub** [comment]
Sorry but even with defining the intervals or attaching a larger poplation still get no sufficient plots. 

Try with attached population

**Comment by pchelle** [comment]
Using the following line of code before `runWorkflow`: 
__`popModelWF$plotDemography$settings$xParametersBreaks[[StandardPath$Age]] <- c(seq(0,3,0.5), seq(4,10,1), c(18, 25, 45, 65, 100))`__
I obtain for instance for weight, the following plots:
![children_0_3y-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135097-57cd1b80-edd8-11ea-84da-01bd3439c70c.png)
![children_0_3y-vs-ref-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135122-5dc2fc80-edd8-11ea-97d3-8a31939fb079.png)
![children_3_6y-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135170-6adfeb80-edd8-11ea-9778-8dc8978bc16d.png)
![children_3_6y-vs-ref-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135198-729f9000-edd8-11ea-96e1-13ceb06ee797.png)
![children_6_9y-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135208-76cbad80-edd8-11ea-9f57-9947574b378d.png)
![children_6_9y-vs-ref-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135218-7a5f3480-edd8-11ea-8b68-e0f750a856e3.png)
![single IV administration-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/92135227-7df2bb80-edd8-11ea-97f8-39d63ab20b98.png)

**Comment by ThomasGaub** [comment]
Thanks for the intervals
I still do not understand why automatic bining does not work for the 100 kids attached

**Comment by msevestre** [comment]
@ThomasGaub Is there anything that needs to be done here for v1?

**Comment by Yuri05** [comment]
>Is there anything that needs to be done here for v1?

@sfrechen @twendl Please comment.

**Comment by TWendl** [comment]
Pierre's workaround is okay for version 1. 
I think the legends need to be adjusted. We should rather print "Population median and [5-95th] percentiles" for the red areas and "Population median and [5-95th] percentiles of the *name of reference* population" for the turquoise areas  whenever demography graphs are plotted!

**Comment by msevestre** [comment]
@TWendl Are you serious? you want to change the legend of the plot NOW?

**Comment by msevestre** [comment]
@pchelle Can you check it out and see if you can do this today or tomorrow?
also it seems to me that there is an extra space in the caption

![image](https://user-images.githubusercontent.com/1041237/93236035-5858a100-f74c-11ea-8a1b-e62f1c44a80a.png)

Between Simulated and median

**Comment by TWendl** [comment]
@msevestre Sorry, I realized it today!

**Comment by msevestre** [comment]
This will delay the release for testing then. @pchelle  please let me know when you can do this

**Comment by pchelle** [comment]
@TWendl , I have updated the code for the legend, let me know if this is what you were expecting:

Figure 20: Age-dependence of Weight for children_6_9y in comparison to single IV administration. Profiles are plotted in a logarithmic scale.
![children_6_9y-vs-ref-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/93249212-f3f30d00-f75e-11ea-863e-4d98e0a4bd1b.png)

Figure 22: Age-dependence of Weight for single IV administration. Profiles are plotted in a logarithmic scale.
![single IV administration-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/93249305-17b65300-f75f-11ea-8971-222dbb6a3fa6.png)

Figure 24: Age-dependence of Weight for children_0_3y. Profiles are plotted in a logarithmic scale.
![children_6_9y-Weight-vs-Age-log](https://user-images.githubusercontent.com/45343665/93249289-11c07200-f75f-11ea-9db6-1171c8da727c.png)

**Comment by msevestre** [comment]
@TWendl Is this good like this or not? We can't release without your approval. Please review asap :)
/cc @Yuri05

**Comment by msevestre** [comment]
@TWendl Can you please review before the meeting tomorrow morning ? Thanks mate
